/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import coneccion.CreateConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level ;
import java.util.logging.Logger ;
/**
 *
 * @author DIEGO JUAREZ
 */
public class Cliente extends javax.swing.JFrame {
    CreateConnection coneccionPostgres = new CreateConnection();
    
    PreparedStatement ps;
    String qry= " ";
    ResultSet rs;
 Connection cn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cliente.class.getName());

    /**
     * Creates new form Cliente
     */
    public Cliente() {
         try{
    
        initComponents();
         cn = coneccionPostgres.getConnection();
        } catch(SQLException ex) {
            System.getLogger(Empleado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnguardar = new javax.swing.JButton();
        txtdpi = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnconsultar = new javax.swing.JButton();
        txtidsucursal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpuesto = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtsalario = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        btnguardar1 = new javax.swing.JButton();
        txtcorreo = new javax.swing.JTextField();
        btnactualizar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btneliminar1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnconsultar1 = new javax.swing.JButton();
        txtnombrec = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtnit = new javax.swing.JTextField();
        txtdpic = new javax.swing.JTextField();
        txtid_sucursal = new javax.swing.JTextField();
        txtidc = new javax.swing.JTextField();
        txtfechac = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txttipocliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        btnguardar.setText("Guardar");

        btnactualizar.setText("Actualizar");

        jLabel7.setText("Fecha Contratación:");

        btneliminar.setText("Eliminar");

        jLabel8.setText("ID Sucursal:");

        btnconsultar.setText("Consultar ID");

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("DPI:");

        jLabel4.setText("Puesto:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Empleado");

        jLabel5.setText("Salario:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnguardar1.setText("Guardar");
        btnguardar1.addActionListener(this::btnguardar1ActionPerformed);

        btnactualizar1.setText("Actualizar");
        btnactualizar1.addActionListener(this::btnactualizar1ActionPerformed);

        jLabel9.setText("Correo:");

        btneliminar1.setText("Eliminar");
        btneliminar1.addActionListener(this::btneliminar1ActionPerformed);

        jLabel10.setText("ID Sucursal:");

        btnconsultar1.setText("Consultar ID");
        btnconsultar1.addActionListener(this::btnconsultar1ActionPerformed);

        jLabel11.setText("ID:");

        jLabel12.setText("Nombre:");

        jLabel13.setText("DPI:");

        jLabel14.setText("Telefono:");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel16.setText("NIT:");

        jLabel17.setText("Fecha ingreso:");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("Clientes");

        jLabel19.setText("Tipo de cliente");

        jLabel20.setText("Carnet: 1290-25-3463");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnguardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttipocliente, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtid_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfechac, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtdpic, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnactualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnconsultar1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtidc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtdpic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txttipocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtfechac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtid_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar1)
                    .addComponent(btnactualizar1)
                    .addComponent(btneliminar1)
                    .addComponent(btnconsultar1))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        // TODO add your handling code here:
         try{

            int id_cliente= Integer.parseInt(txtidc.getText());
            String nombre = txtnombrec.getText();
            String nit = txtnit.getText();
            String dpi = txtdpic.getText();
          
            String telefono = txttelefono.getText();
            String correo = txtcorreo.getText();
            String tipo_cliente = txttipocliente.getText();
            String fecha_registro = txtfechac.getText();
             int id_sucursal = Integer.parseInt(txtid_sucursal.getText());
           
            
            qry = "INSERT INTO cliente(id_cliente,nombre,nit,dpi,telefono, correo, tipo_cliente, fecha_registro, id_sucursal) values (?,?,?,?,?,?,?,?,?)";
            ps= cn.prepareStatement(qry);
            ps.setInt(1, id_cliente);
            ps.setString(2, nombre);
            ps.setString(3, nit);
            ps.setString(4, dpi );
            ps.setString(5, telefono);
            ps.setString(6, correo);
            ps.setString(7, tipo_cliente);
            ps.setString(8, fecha_registro);
            ps.setInt(9, id_sucursal);
            
            int resultado = ps.executeUpdate();


        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnguardar1ActionPerformed

    private void btnconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar1ActionPerformed
        // TODO add your handling code here:
        try{ 
        String input = JOptionPane.showInputDialog("ID a consultar");
                       if (input != null) {
        int id_cliente = Integer.parseInt(input);
       qry = "Select * from public.cliente where id_cliente = ?";
       ps = cn.prepareStatement(qry);
           ps.setInt(1, id_cliente);
           rs = ps.executeQuery();
           
           if (rs.next()){
               txtidc.setText(rs.getString(1));
               txtnombrec.setText(rs.getString(2));
               txtnit.setText(rs.getString(3));
               txtdpic.setText(rs.getString(4));
               txttelefono.setText(rs.getString(5));
               txtcorreo.setText(rs.getString(6));
               txttipocliente.setText(rs.getString(7));
               txtfechac.setText(rs.getString(8));
               txtidsucursal.setText(rs.getString(9));

          
           }else{
               JOptionPane.showMessageDialog(null, "No se encontró el ID");
               return;
           }
                       }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
                               }
    }//GEN-LAST:event_btnconsultar1ActionPerformed

    private void btnactualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizar1ActionPerformed
        // TODO add your handling code here:
        try{
         int id_cliente= Integer.parseInt(txtidc.getText());
            String nombre = txtnombrec.getText();
            String nit = txtnit.getText();
            String dpi = txtdpic.getText();
            String telefono = txttelefono.getText();
            String correo = txtcorreo.getText();
            String tipo_cliente = txttipocliente.getText();
            String fecha_registro = txtfechac.getText();
             int id_sucursal = Integer.parseInt(txtid_sucursal.getText());
            
            qry = "UPDATE cliente"
                     + " SET nombre= ?, "
                   + " nit = ? , "
                   + " dpi = ? ,"
                    +" telefono = ? ,"
                    +" correo= ?, "
                    +" tipo_cliente= ?, "
                    +" fecha_registro= ?, "
                    +" id_sucursal = ? "
                   + "where id_cliente= ? ";
            
             ps = cn.prepareStatement(qry);
                  
          
            ps.setString(1, nombre);
            ps.setString(2, nit);
            ps.setString(3, dpi);
            ps.setString(4, telefono);
            ps.setString(5, correo);
            ps.setString(6, tipo_cliente);
            ps.setString(7, fecha_registro);
            ps.setInt(8, id_sucursal);
            ps.setInt(9, id_cliente);
             int resultado =ps.executeUpdate();
                       if (resultado == 1){
               JOptionPane.showMessageDialog(null, "Dato actualizado correctamente");
           }else{
               JOptionPane.showMessageDialog(null, "Dato actualizado incorrectamente");
           }
           ps.close();

            
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnactualizar1ActionPerformed

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
        // TODO add your handling code here:
         try{
        String input = JOptionPane.showInputDialog("Registro a Eliminar");
        if(input != null){
    int id_cliente = Integer.parseInt(input);
                qry = "delete from public.cliente where id_cliente = ?";

                    
ps = cn.prepareStatement(qry);
ps.setInt(1, id_cliente);
ps.executeUpdate();

 int resultado =ps.executeUpdate();
                       if (resultado == 1){
    System.out.println("Registro eliminado exitosamente ");
}else{
    System.out.println("Registro no encontrado ");
}
    }           
}catch (SQLException ex){
        System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btneliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnactualizar1;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnconsultar1;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtdpic;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtfechac;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid_sucursal;
    private javax.swing.JTextField txtidc;
    private javax.swing.JTextField txtidsucursal;
    private javax.swing.JTextField txtnit;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombrec;
    private javax.swing.JTextField txtpuesto;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttipocliente;
    // End of variables declaration//GEN-END:variables
}
