/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import coneccion.CreateConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level ;
import java.util.logging.Logger ;
/**
 *
 * @author DIEGO JUAREZ
 */
public class Trabajador extends javax.swing.JFrame {
     CreateConnection coneccionPostgres = new CreateConnection();
    
    PreparedStatement ps;
    String qry= " ";
    ResultSet rs;
 Connection cn;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Trabajador.class.getName());

    /**
     * Creates new form Trabajador
     */
    public Trabajador() {
        try{
    
        initComponents();
         cn = coneccionPostgres.getConnection();
        } catch(SQLException ex) {
            System.getLogger(Empleado.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpuesto = new javax.swing.JTextField();
        txtsalario = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtdpi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidsucursal = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setText("Carnet: 1290-25-3463");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Empleado");

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(this::btnguardarActionPerformed);

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(this::btnactualizarActionPerformed);

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(this::btneliminarActionPerformed);

        btnconsultar.setText("Consultar ID");
        btnconsultar.addActionListener(this::btnconsultarActionPerformed);

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("DPI:");

        jLabel4.setText("Puesto:");

        jLabel5.setText("Salario:");

        jLabel7.setText("Fecha Contratación:");

        jLabel8.setText("ID Sucursal:");

        jLabel10.setText("Carnet: 1290-25-3463");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnconsultar)))
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(txtidsucursal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtdpi)
                        .addComponent(txtnombre)
                        .addComponent(txtpuesto)
                        .addComponent(txtsalario, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtidsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnactualizar)
                    .addComponent(btneliminar)
                    .addComponent(btnconsultar))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtdpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(183, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        try{

            int id_empleado= Integer.parseInt(txtid.getText());
            String nombre = txtnombre.getText();
            String dpi = txtdpi.getText();
            String puesto = txtpuesto.getText();
            double salario = Double.parseDouble(txtsalario.getText() );
            String fecha_contratacion = txtfecha.getText();
             int id_sucursal = Integer.parseInt(txtidsucursal.getText());
           
            
            qry = "INSERT INTO empleado(id_empleado,nombre,dpi,puesto,salario, fecha_contratacion, id_sucursal) values (?,?,?,?,?,?,?)";
            ps= cn.prepareStatement(qry);
            ps.setInt(1, id_empleado);
            ps.setString(2, nombre);
            ps.setString(3, dpi);
            ps.setString(4, puesto);
            ps.setDouble(5, salario);
            ps.setString(6, fecha_contratacion);
            ps.setInt(7, id_sucursal);
            
            int resultado = ps.executeUpdate();


        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
                try{ 
        String input = JOptionPane.showInputDialog("ID a consultar");
                       if (input != null) {
        int id_empleado = Integer.parseInt(input);
       qry = "Select * from public.empleado where id_empleado = ?";
       ps = cn.prepareStatement(qry);
           ps.setInt(1, id_empleado);
           rs = ps.executeQuery();
           
           if (rs.next()){
               txtid.setText(rs.getString(1));
               txtnombre.setText(rs.getString(2));
               txtdpi.setText(rs.getString(3));
               txtpuesto.setText(rs.getString(4));
               txtsalario.setText(rs.getString(5));
               txtfecha.setText(rs.getString(6));
               txtidsucursal.setText(rs.getString(7));

          
           }else{
               JOptionPane.showMessageDialog(null, "No se encontró el ID");
               return;
           }
                       }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
                               }
                    
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        try{
 int id_empleado = Integer.parseInt(txtid.getText());
    String nombre = txtnombre.getText();
    String dpi = txtdpi.getText();
    String puesto = txtpuesto.getText();
    double salario = Double.parseDouble(txtsalario.getText());
    String fecha_contratacion = txtfecha.getText();
    int id_sucursal = Integer.parseInt(txtidsucursal.getText());

    qry = "UPDATE empleado "
            + "SET nombre=?, "
            +"dpi=?, "
            +"puesto=?, "
            +"salario=?, "
            +"fecha_contratacion=?, "
            +"id_sucursal=? "
            +"WHERE id_empleado=?";

    ps = cn.prepareStatement(qry);

    ps.setString(1, nombre);
    ps.setString(2, dpi);
    ps.setString(3, puesto);
    ps.setDouble(4, salario);
    ps.setString(5, fecha_contratacion);
    ps.setInt(6, id_sucursal);
    ps.setInt(7, id_empleado);

    int resultado = ps.executeUpdate();

    if (resultado == 1) {
        JOptionPane.showMessageDialog(null, "Dato actualizado correctamente");
    } else {
        JOptionPane.showMessageDialog(null, "El dato no se actualizó");
    }

    ps.close();

} catch (SQLException ex) {
    System.out.println(ex.getMessage());
}
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
         try{
        String input = JOptionPane.showInputDialog("Registro a Eliminar");
        if(input != null){
    int id_empleado = Integer.parseInt(input);
                qry = "delete from public.empleado where id_empleado = ?";

                    
ps = cn.prepareStatement(qry);
ps.setInt(1, id_empleado);
ps.executeUpdate();

 int resultado =ps.executeUpdate();
                       if (resultado == 1){
    System.out.println("Registro eliminado exitosamente ");
}else{
    System.out.println("Registro no encontrado ");
}
    }           
}catch (SQLException ex){
        System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btneliminarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Trabajador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidsucursal;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpuesto;
    private javax.swing.JTextField txtsalario;
    // End of variables declaration//GEN-END:variables
}
